//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knightApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Athletes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Athletes()
        {
            this.AthletesInTheTournaments = new HashSet<AthletesInTheTournaments>();
            this.AthletesInTheTournaments1 = new HashSet<AthletesInTheTournaments>();
            this.SortsOfSports1 = new HashSet<SortsOfSports>();
            this.TrainingPrograms = new HashSet<TrainingPrograms>();
        }
    
        public int id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string patronymic { get; set; }
        public Nullable<int> discharge_id { get; set; }
        public Nullable<int> title_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> image_id { get; set; }
        public Nullable<int> sortOfSport_id { get; set; }
    
        public virtual Discharges Discharges { get; set; }
        public virtual SortsOfSports SortsOfSports { get; set; }
        public virtual Titles Titles { get; set; }
        public virtual Users_images Users_images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AthletesInTheTournaments> AthletesInTheTournaments { get; set; }
        public virtual Teams Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AthletesInTheTournaments> AthletesInTheTournaments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortsOfSports> SortsOfSports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingPrograms> TrainingPrograms { get; set; }
    }
}
