//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knightApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthletesInTheTournaments
    {
        public int athlete_id { get; set; }
        public int tournament_id { get; set; }
    
        public virtual Athletes Athletes { get; set; }
        public virtual Athletes Athletes1 { get; set; }
        public virtual Tournaments Tournaments { get; set; }
        public virtual Tournaments Tournaments1 { get; set; }
    }
}
