//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knightApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnightDBEntities : DbContext
    {
        public KnightDBEntities()
            : base("name=KnightDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Athletes> Athletes { get; set; }
        public virtual DbSet<AthletesInTheTournaments> AthletesInTheTournaments { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Discharges> Discharges { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Premises> Premises { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SortsOfSports> SortsOfSports { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Titles> Titles { get; set; }
        public virtual DbSet<Tournaments> Tournaments { get; set; }
        public virtual DbSet<TrainingPrograms> TrainingPrograms { get; set; }
        public virtual DbSet<Transfers> Transfers { get; set; }
        public virtual DbSet<Type_of_car> Type_of_car { get; set; }
        public virtual DbSet<TypesOfSports> TypesOfSports { get; set; }
        public virtual DbSet<TypesOfTraining> TypesOfTraining { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_images> Users_images { get; set; }
    }
}
