//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knightApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingPrograms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingPrograms()
        {
            this.Athletes = new HashSet<Athletes>();
        }
    
        public int id { get; set; }
        public double duration_in_hours { get; set; }
        public Nullable<int> staffer_id { get; set; }
        public Nullable<int> premise_id { get; set; }
        public Nullable<int> sort_of_sport_id { get; set; }
        public Nullable<int> type_of_training_id { get; set; }
    
        public virtual Premises Premises { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual TypesOfTraining TypesOfTraining { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Athletes> Athletes { get; set; }
    }
}
